import { Inter } from "next/font/google";
import "./globals.css";
import Particles from "../app/Particles/page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hammad-three-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      {children}<Particles/>
      </body>
    </html>
  );
}
